using System.IO;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

/// <summary>
/// Deletes large, unwanted build artifacts like Burst debug info and IL2CPP backup folders.
/// These folders are typically used for debugging symbols but can be several hundred MBs.
/// </summary>
public class BuildCleanupPostProcessor : IPostprocessBuildWithReport
{
    // High callback order to ensure it runs after other post-processors
    public int callbackOrder => 1000;

    public void OnPostprocessBuild(BuildReport report)
    {
        if (report.summary.result != BuildResult.Succeeded)
            return;

        string outputPath = report.summary.outputPath;
        if (string.IsNullOrEmpty(outputPath))
            return;

        string buildDirectory;
        if (File.Exists(outputPath))
            buildDirectory = Path.GetDirectoryName(outputPath);
        else if (Directory.Exists(outputPath))
            buildDirectory = outputPath;
        else
            return;

        if (string.IsNullOrEmpty(buildDirectory))
            return;

        // Common suffixes for unwanted folders generated by IL2CPP and Burst
        string[] unwantedSuffixes = 
        {
            "_BackUpThisFolder_ButDontShipItWithYourGame",
            "_BurstDebugInformation_DoNotShip"
        };

        Debug.Log($"[BuildCleanup] Checking for unwanted artifacts in: {buildDirectory}");

        // Search for folders with these suffixes in the build directory
        try
        {
            string[] directories = Directory.GetDirectories(buildDirectory);
            foreach (var dir in directories)
            {
                string dirName = Path.GetFileName(dir);
                foreach (var suffix in unwantedSuffixes)
                {
                    if (dirName.EndsWith(suffix, System.StringComparison.OrdinalIgnoreCase))
                    {
                        DeleteDirectory(dir);
                    }
                }
            }
        }
        catch (System.Exception e)
        {
            Debug.LogWarning($"[BuildCleanup] Error scanning build directory: {e.Message}");
        }
    }

    private void DeleteDirectory(string path)
    {
        try
        {
            if (Directory.Exists(path))
            {
                Debug.Log($"[BuildCleanup] Deleting unwanted build artifact: {path}");
                Directory.Delete(path, true);
            }
        }
        catch (System.Exception e)
        {
            Debug.LogWarning($"[BuildCleanup] Failed to delete artifact at {path}: {e.Message}");
        }
    }
}
