// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/string/client_string.csv
#if UNITY_EDITOR
namespace Game.Editor
{
    // Keys from client_string.csv — import with: using static Game.Editor.StringIds
    internal static class StringIds
    {
        // app
        public const string AppTitle = "app.title";

        // boot
        public const string BootLoading = "boot.loading";

        // common
        public const string CommonBtnCancel = "common.btn_cancel";
        public const string CommonBtnConfirm = "common.btn_confirm";
        public const string CommonBtnOk = "common.btn_ok";
        public const string CommonBtnRetry = "common.btn_retry";
        public const string CommonBtnNext = "common.btn_next";
        public const string CommonBtnPlay = "common.btn_play";
        public const string CommonBtnClose = "common.btn_close";
        public const string CommonBtnMap = "common.btn_map";
        public const string CommonSettings = "common.settings";
        public const string CommonGuest = "common.guest";
        public const string CommonBtnClaim = "common.btn_claim";

        // error
        public const string ErrorNetworkCheck = "error.network_check";

        // popup
        public const string PopupRewardTitle = "popup.reward.title";
        public const string PopupReloginTitle = "popup.relogin.title";
        public const string PopupReloginBtnRelogin = "popup.relogin.btn_relogin";
        public const string PopupReloginBtnGuest = "popup.relogin.btn_guest";
        public const string PopupResultTitle = "popup.result.title";
        public const string PopupFailTitle = "popup.fail.title";
        public const string PopupFailBtnContinue = "popup.fail.btn_continue";
        public const string PopupFailBtnForfeit = "popup.fail.btn_forfeit";
        public const string PopupPauseTitle = "popup.pause.title";
        public const string PopupPauseBtnResume = "popup.pause.btn_resume";
        public const string PopupPauseBtnRestart = "popup.pause.btn_restart";
        public const string PopupPauseBtnStageSelect = "popup.pause.btn_stage_select";
        public const string PopupSettingsBgm = "popup.settings.bgm";
        public const string PopupSettingsSfx = "popup.settings.sfx";
        public const string PopupSettingsScreenShake = "popup.settings.screen_shake";
        public const string PopupSettingsAccount = "popup.settings.account";
        public const string PopupAccountBtnLink = "popup.account.btn_link";
        public const string PopupAccountBtnSwitch = "popup.account.btn_switch";
        public const string PopupAccountBtnLogout = "popup.account.btn_logout";
        public const string PopupStageInfoTitle = "popup.stage_info.title";
        public const string PopupStageInfoBestStars = "popup.stage_info.best_stars";
        public const string PopupStageInfoBestMoves = "popup.stage_info.best_moves";
        public const string PopupStageInfoNoRecord = "popup.stage_info.no_record";
        public const string PopupResultFailed = "popup.result.failed";
        public const string PopupResultClearTitle = "popup.result.clear_title";
        public const string PopupResultRatio = "popup.result.ratio";
        public const string PopupResultTurns = "popup.result.turns";
        public const string PopupResultRank = "popup.result.rank";
        public const string PopupResultNewBest = "popup.result.new_best";
        public const string PopupFailContinueTurns = "popup.fail.continue_turns";
        public const string PopupStaminaTitle = "popup.stamina.title";
        public const string PopupStaminaWatchAd = "popup.stamina.watch_ad";
        public const string PopupStaminaUnlimited = "popup.stamina.unlimited";

        // lobby
        public const string LobbyRankingStarsTitle = "lobby.ranking.stars_title";
        public const string LobbyRankingStageTitle = "lobby.ranking.stage_title";
        public const string LobbyRankingMyRankEmpty = "lobby.ranking.my_rank_empty";
        public const string LobbyRankingMyRankFormat = "lobby.ranking.my_rank_format";
        public const string LobbyRankingLoading = "lobby.ranking.loading";
        public const string LobbyRankingNoData = "lobby.ranking.no_data";
        public const string LobbyRankingDefaultTitle = "lobby.ranking.default_title";
        public const string LobbyRankingUnavailable = "lobby.ranking.unavailable";
        public const string LobbyRankingTabStars = "lobby.ranking.tab_stars";
        public const string LobbyRankingTabMaxStage = "lobby.ranking.tab_max_stage";

        // ingame
        public const string IngameTurnsLabel = "ingame.turns_label";

        // nav
        public const string NavHome = "nav.home";
        public const string NavShop = "nav.shop";
        public const string NavRanking = "nav.ranking";

        // stamina
        public const string StaminaMax = "stamina.max";
        public const string StaminaNextCharge = "stamina.next_charge";

        // item
        public const string ItemNameAddTurn = "item.name.add_turn";
        public const string ItemDescAddTurn = "item.desc.add_turn";
        public const string ItemNameBomb = "item.name.bomb";
        public const string ItemDescBomb = "item.desc.bomb";
        public const string ItemNameHRocket = "item.name.h_rocket";
        public const string ItemDescHRocket = "item.desc.h_rocket";
        public const string ItemNameColorSweep = "item.name.color_sweep";
        public const string ItemDescColorSweep = "item.desc.color_sweep";
        public const string ItemNameRowShift = "item.name.row_shift";
        public const string ItemDescRowShift = "item.desc.row_shift";
        public const string ItemNameCellSwap = "item.name.cell_swap";
        public const string ItemDescCellSwap = "item.desc.cell_swap";

        // tut
        public const string TutTapGroup = "tut.tap_group";
        public const string TutGravityExplain = "tut.gravity_explain";
        public const string TutTurnExplain = "tut.turn_explain";
        public const string TutRatioExplain = "tut.ratio_explain";
        public const string TutStarExplain = "tut.star_explain";
        public const string TutFreeTap = "tut.free_tap";
        public const string TutProtectorWhat = "tut.protector_what";
        public const string TutProtectorHow = "tut.protector_how";
        public const string TutCoreWarning = "tut.core_warning";
        public const string TutObstacleWhat = "tut.obstacle_what";
        public const string TutItemHintPrompt = "tut.item_hint_prompt";
        public const string TutItemBombEffect = "tut.item_bomb_effect";
    }
}
#endif
