// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/string/client_string.csv
#if UNITY_EDITOR
namespace Game.Editor
{
    // Keys from client_string.csv — import with: using static Game.Editor.StringIds
    internal static class StringIds
    {
        // app
        public const string AppTitle = "app.title";

        // boot
        public const string BootLoading = "boot.loading";
        public const string BootNewGuestSession = "boot.new_guest_session";

        // common
        public const string CommonBtnCancel = "common.btn_cancel";
        public const string CommonBtnConfirm = "common.btn_confirm";
        public const string CommonBtnOk = "common.btn_ok";
        public const string CommonBtnRetry = "common.btn_retry";
        public const string CommonBtnNext = "common.btn_next";
        public const string CommonBtnPlay = "common.btn_play";
        public const string CommonBtnClose = "common.btn_close";
        public const string CommonBtnMap = "common.btn_map";
        public const string CommonSettings = "common.settings";
        public const string CommonGuest = "common.guest";
        public const string CommonBtnClaim = "common.btn_claim";
        public const string CommonLoading = "common.loading";
        public const string CommonGold = "common.gold";
        public const string CommonBtnUnlock = "common.btn_unlock";
        public const string CommonBtnSwitch = "common.btn_switch";

        // error
        public const string ErrorNetworkCheck = "error.network_check";
        public const string ErrorAdFailed = "error.ad_failed";

        // popup
        public const string PopupNetworkErrorTitle = "popup.network_error.title";
        public const string PopupRewardTitle = "popup.reward.title";
        public const string PopupReloginTitle = "popup.relogin.title";
        public const string PopupReloginBtnRelogin = "popup.relogin.btn_relogin";
        public const string PopupReloginBtnGuest = "popup.relogin.btn_guest";
        public const string PopupResultTitle = "popup.result.title";
        public const string PopupFailTitle = "popup.fail.title";
        public const string PopupFailBtnContinue = "popup.fail.btn_continue";
        public const string PopupFailBtnForfeit = "popup.fail.btn_forfeit";
        public const string PopupPauseTitle = "popup.pause.title";
        public const string PopupPauseBtnResume = "popup.pause.btn_resume";
        public const string PopupPauseBtnRestart = "popup.pause.btn_restart";
        public const string PopupPauseBtnStageSelect = "popup.pause.btn_stage_select";
        public const string PopupSettingsBgm = "popup.settings.bgm";
        public const string PopupSettingsSfx = "popup.settings.sfx";
        public const string PopupSettingsScreenShake = "popup.settings.screen_shake";
        public const string PopupSettingsAccount = "popup.settings.account";
        public const string PopupAccountBtnLink = "popup.account.btn_link";
        public const string PopupAccountBtnSwitch = "popup.account.btn_switch";
        public const string PopupAccountRestartTitle = "popup.account_restart.title";
        public const string PopupAccountRestartBody = "popup.account_restart.body";
        public const string PopupAccountRestartConfirm = "popup.account_restart.confirm";
        public const string PopupAccountConflictTitle = "popup.account_conflict.title";
        public const string PopupAccountConflictBody = "popup.account_conflict.body";
        public const string PopupAccountConflictLocalLabel = "popup.account_conflict.local_label";
        public const string PopupAccountConflictCloudLabel = "popup.account_conflict.cloud_label";
        public const string PopupAccountConflictStageFmt = "popup.account_conflict.stage_fmt";
        public const string PopupAccountConflictGoldFmt = "popup.account_conflict.gold_fmt";
        public const string PopupAccountConflictStarsFmt = "popup.account_conflict.stars_fmt";
        public const string PopupAccountConflictItemsFmt = "popup.account_conflict.items_fmt";
        public const string PopupAccountConflictBtnKeepLocal = "popup.account_conflict.btn_keep_local";
        public const string PopupAccountConflictBtnKeepCloud = "popup.account_conflict.btn_keep_cloud";
        public const string PopupStageInfoTitle = "popup.stage_info.title";
        public const string PopupStageInfoBestStars = "popup.stage_info.best_stars";
        public const string PopupStageInfoBestMoves = "popup.stage_info.best_moves";
        public const string PopupStageInfoNoRecord = "popup.stage_info.no_record";
        public const string PopupResultFailed = "popup.result.failed";
        public const string PopupResultClearTitle = "popup.result.clear_title";
        public const string PopupResultRatio = "popup.result.ratio";
        public const string PopupResultTurns = "popup.result.turns";
        public const string PopupResultRank = "popup.result.rank";
        public const string PopupResultNewBest = "popup.result.new_best";
        public const string PopupFailContinueTurns = "popup.fail.continue_turns";
        public const string PopupStaminaTitle = "popup.stamina.title";
        public const string PopupStaminaWatchAd = "popup.stamina.watch_ad";
        public const string PopupStaminaUnlimited = "popup.stamina.unlimited";
        public const string PopupAccountBtnSave = "popup.account.btn_save";
        public const string PopupAccountLabelNickname = "popup.account.label_nickname";
        public const string PopupAccountLabelSelectAvatar = "popup.account.label_select_avatar";
        public const string PopupAccountTabAvatars = "popup.account.tab_avatars";
        public const string PopupAccountTabBoardSkins = "popup.account.tab_board_skins";
        public const string PopupAccountPlaceholderNickname = "popup.account.placeholder_nickname";
        public const string PopupFailWatchAd = "popup.fail.watch_ad";
        public const string PopupSettingsHaptic = "popup.settings.haptic";
        public const string PopupSettingsLanguage = "popup.settings.language";
        public const string PopupSettingsLangKO = "popup.settings.lang.KO";
        public const string PopupSettingsLangEN = "popup.settings.lang.EN";
        public const string PopupFailRemainingRevivesFmt = "popup.fail.remaining_revives_fmt";
        public const string PopupAccountConfirmUnlockThemeTitle = "popup.account.confirm_unlock_theme_title";
        public const string PopupAccountConfirmUnlockThemeBodyFmt = "popup.account.confirm_unlock_theme_body_fmt";
        public const string PopupAccountConfirmFailedUnlockTheme = "popup.account.confirm_failed_unlock_theme";
        public const string PopupAccountConfirmUnlockAvatarTitle = "popup.account.confirm_unlock_avatar_title";
        public const string PopupAccountConfirmUnlockAvatarBodyFmt = "popup.account.confirm_unlock_avatar_body_fmt";
        public const string PopupAccountConfirmFailedUnlockAvatar = "popup.account.confirm_failed_unlock_avatar";
        public const string PopupAccountConfirmSwitchTitle = "popup.account.confirm_switch_title";
        public const string PopupAccountConfirmSwitchBody = "popup.account.confirm_switch_body";
        public const string PopupStaminaOutOfLives = "popup.stamina.out_of_lives";
        public const string PopupStaminaWatchAdBody = "popup.stamina.watch_ad_body";
        public const string PopupAccountChooseAvatar = "popup.account.choose_avatar";
        public const string PopupAccountChooseBoardTheme = "popup.account.choose_board_theme";
        public const string PopupBootContinueAsGuestTitle = "popup.boot.continue_as_guest_title";
        public const string PopupBootContinueAsGuestBody = "popup.boot.continue_as_guest_body";

        // toast
        public const string ToastAccountAlreadyActive = "toast.account_already_active";
        public const string ToastInsufficientGold = "toast.insufficient_gold";
        public const string ToastStageLocked = "toast.stage_locked";
        public const string ToastBoosterPurchased = "toast.booster_purchased";
        public const string ToastRevived = "toast.revived";
        public const string ToastAdCancelled = "toast.ad_cancelled";
        public const string ToastLifeGained = "toast.life_gained";
        public const string ToastChapterUnlockRequirement = "toast.chapter_unlock_requirement";
        public const string ToastChestClaimed = "toast.chest_claimed";
        public const string ToastNicknameLengthError = "toast.nickname_length_error";
        public const string ToastNicknameCharError = "toast.nickname_char_error";
        public const string ToastNicknameUpdated = "toast.nickname_updated";
        public const string ToastNicknameUpdateFailed = "toast.nickname_update_failed";
        public const string ToastThemeNotEnoughGold = "toast.theme_not_enough_gold";
        public const string ToastThemeEquipped = "toast.theme_equipped";
        public const string ToastThemeEquipFailed = "toast.theme_equip_failed";
        public const string ToastThemeUnlocked = "toast.theme_unlocked";
        public const string ToastAvatarNotEnoughGold = "toast.avatar_not_enough_gold";
        public const string ToastAvatarEquipped = "toast.avatar_equipped";
        public const string ToastAvatarEquipFailed = "toast.avatar_equip_failed";
        public const string ToastAvatarUnlocked = "toast.avatar_unlocked";
        public const string ToastGoogleSigninNotConfigured = "toast.google_signin_not_configured";
        public const string ToastGoogleSigninUnavailable = "toast.google_signin_unavailable";
        public const string ToastAccountLinked = "toast.account_linked";
        public const string ToastAccountSwitched = "toast.account_switched";
        public const string ToastGoogleSigninAndroidOnly = "toast.google_signin_android_only";
        public const string ToastItemSpendFailed = "toast.item_spend_failed";
        public const string ToastChestClaimFailed = "toast.chest_claim_failed";

        // lobby
        public const string LobbyRankingStarsTitle = "lobby.ranking.stars_title";
        public const string LobbyRankingStageTitle = "lobby.ranking.stage_title";
        public const string LobbyRankingMyRankEmpty = "lobby.ranking.my_rank_empty";
        public const string LobbyRankingMyRankFormat = "lobby.ranking.my_rank_format";
        public const string LobbyRankingLoading = "lobby.ranking.loading";
        public const string LobbyRankingNoData = "lobby.ranking.no_data";
        public const string LobbyRankingDefaultTitle = "lobby.ranking.default_title";
        public const string LobbyRankingUnavailable = "lobby.ranking.unavailable";
        public const string LobbyRankingTabStars = "lobby.ranking.tab_stars";
        public const string LobbyRankingTabMaxStage = "lobby.ranking.tab_max_stage";

        // ingame
        public const string IngameTurnsLabel = "ingame.turns_label";
        public const string IngameCellsLabel = "ingame.cells_label";

        // nav
        public const string NavHome = "nav.home";
        public const string NavShop = "nav.shop";
        public const string NavRanking = "nav.ranking";

        // stamina
        public const string StaminaMax = "stamina.max";
        public const string StaminaNextCharge = "stamina.next_charge";

        // item
        public const string ItemNameAddTurn = "item.name.add_turn";
        public const string ItemDescAddTurn = "item.desc.add_turn";
        public const string ItemNameBomb = "item.name.bomb";
        public const string ItemDescBomb = "item.desc.bomb";
        public const string ItemNameHRocket = "item.name.h_rocket";
        public const string ItemDescHRocket = "item.desc.h_rocket";
        public const string ItemNameColorSweep = "item.name.color_sweep";
        public const string ItemDescColorSweep = "item.desc.color_sweep";
        public const string ItemNameRowShift = "item.name.row_shift";
        public const string ItemDescRowShift = "item.desc.row_shift";
        public const string ItemNameCellSwap = "item.name.cell_swap";
        public const string ItemDescCellSwap = "item.desc.cell_swap";

        // tut
        public const string TutTapGroup = "tut.tap_group";
        public const string TutGravityExplain = "tut.gravity_explain";
        public const string TutTurnExplain = "tut.turn_explain";
        public const string TutRatioExplain = "tut.ratio_explain";
        public const string TutStarExplain = "tut.star_explain";
        public const string TutFreeTap = "tut.free_tap";
        public const string TutProtectorWhat = "tut.protector_what";
        public const string TutProtectorHow = "tut.protector_how";
        public const string TutCoreWarning = "tut.core_warning";
        public const string TutObstacleWhat = "tut.obstacle_what";
        public const string TutItemHintPrompt = "tut.item_hint_prompt";
        public const string TutItemBombEffect = "tut.item_bomb_effect";

        // chapter
        public const string ChapterNameFmt = "chapter.name_fmt";
        public const string ChapterLocked = "chapter.locked";

        // shop
        public const string ShopComingSoon = "shop.coming_soon";
        public const string ShopStarterPack = "shop.starter_pack";
        public const string ShopItemBundle = "shop.item_bundle";
        public const string ShopRemoveAds = "shop.remove_ads";
    }
}
#endif
