// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/string/client_string.csv
#if UNITY_EDITOR
namespace Game.Editor
{
    // Keys from client_string.csv — import with: using static Game.Editor.StringIds
    internal static class StringIds
    {
        // app
        public const string AppTitle = "app.title";

        // boot
        public const string BootLoading = "boot.loading";

        // common
        public const string CommonBtnCancel = "common.btn_cancel";
        public const string CommonBtnConfirm = "common.btn_confirm";
        public const string CommonBtnOk = "common.btn_ok";
        public const string CommonBtnRetry = "common.btn_retry";
        public const string CommonBtnNext = "common.btn_next";
        public const string CommonBtnPlay = "common.btn_play";
        public const string CommonBtnClose = "common.btn_close";
        public const string CommonBtnMap = "common.btn_map";
        public const string CommonSettings = "common.settings";
        public const string CommonGuest = "common.guest";

        // error
        public const string ErrorNetworkCheck = "error.network_check";

        // popup
        public const string PopupRewardTitle = "popup.reward.title";
        public const string PopupReloginTitle = "popup.relogin.title";
        public const string PopupReloginBtnRelogin = "popup.relogin.btn_relogin";
        public const string PopupReloginBtnGuest = "popup.relogin.btn_guest";
        public const string PopupResultTitle = "popup.result.title";
        public const string PopupFailTitle = "popup.fail.title";
        public const string PopupFailBtnContinue = "popup.fail.btn_continue";
        public const string PopupFailBtnForfeit = "popup.fail.btn_forfeit";
        public const string PopupPauseTitle = "popup.pause.title";
        public const string PopupPauseBtnResume = "popup.pause.btn_resume";
        public const string PopupPauseBtnRestart = "popup.pause.btn_restart";
        public const string PopupPauseBtnStageSelect = "popup.pause.btn_stage_select";
        public const string PopupSettingsBgm = "popup.settings.bgm";
        public const string PopupSettingsSfx = "popup.settings.sfx";
        public const string PopupSettingsScreenShake = "popup.settings.screen_shake";
        public const string PopupSettingsAccount = "popup.settings.account";
        public const string PopupAccountBtnLink = "popup.account.btn_link";
        public const string PopupAccountBtnSwitch = "popup.account.btn_switch";
        public const string PopupAccountBtnLogout = "popup.account.btn_logout";
    }
}
#endif
