// AUTO-GENERATED by gen:data — do not edit
#nullable enable
using ProjectLink.Domain.StaticData;
using ProjectLink.Generated.Data;

namespace ProjectLink.Infrastructure.Data;

public partial class StaticDataService
{
    private IReadOnlyDictionary<byte, ColorPaletteData> _colorPalettes = new Dictionary<byte, ColorPaletteData>();
    private IReadOnlyDictionary<int, StageData> _stages = new Dictionary<int, StageData>();

    private void InitGeneratedData(string dataRoot)
    {
        var commonPath = System.IO.Path.Combine(dataRoot, "common");
        var stagePath = System.IO.Path.Combine(dataRoot, "stage");

        _colorPalettes = ColorPaletteLoader.LoadAll(System.IO.Path.Combine(commonPath, "color_palette.csv"))
            .ToDictionary(r => r.color_id, r => new ColorPaletteData
            {
                ColorId = r.color_id,
            });
        _stages = StageLoader.LoadAll(System.IO.Path.Combine(stagePath, "stage.csv"))
            .ToDictionary(r => r.stage_id, r => new StageData
            {
                StageId = r.stage_id,
            });
    }

    public ColorPaletteData? GetColorPalette(byte color_id) => _colorPalettes.GetValueOrDefault(color_id);
    public IReadOnlyList<ColorPaletteData> GetAllColorPalettes() => _colorPalettes.Values.ToList();
    public StageData? GetStage(int stage_id) => _stages.GetValueOrDefault(stage_id);
    public IReadOnlyList<StageData> GetAllStages() => _stages.Values.ToList();
}