-- Generated by db-generator | DB: mysql | 2026-06-07T18:13:47.493Z

CREATE TABLE IF NOT EXISTS `user_tutorial_progress` (
  `user_id` BIGINT NOT NULL,
  `tutorial_id` INT NOT NULL,
  `viewed_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`user_id`, `tutorial_id`),
  KEY `idx_user_tutorial_progress_user_id` (`user_id`),
  CONSTRAINT `fk_user_tutorial_progress_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tracks completed tutorial steps per user.';

-- sessions: removed from schema (review before applying):
-- ALTER TABLE `sessions` DROP INDEX `fk_sessions_user_id`;
