-- Generated by db-generator | DB: mysql | 2026-06-07T17:16:29.428Z

CREATE TABLE IF NOT EXISTS `user_inventory` (
  `user_id` BIGINT NOT NULL,
  `item_id` INT NOT NULL,
  `count` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`user_id`, `item_id`),
  KEY `idx_user_inventory_user_id` (`user_id`),
  CONSTRAINT `fk_user_inventory_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Inventory counts for each booster item type per player.';

-- sessions: removed from schema (review before applying):
-- ALTER TABLE `sessions` DROP INDEX `fk_sessions_user_id`;
