-- Generated by db-generator | DB: mysql | 2026-06-05T08:45:39.085Z

CREATE TABLE IF NOT EXISTS `user_stage_progress` (
  `user_id` BIGINT NOT NULL,
  `stage_id` INT NOT NULL,
  `best_star` INT NOT NULL DEFAULT 0,
  `best_turns_used` INT NULL,
  `first_cleared_at` DATETIME(6) NULL,
  `best_star_updated_at` DATETIME(6) NULL,
  `best_turns_updated_at` DATETIME(6) NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`user_id`, `stage_id`),
  KEY `idx_user_stage_progress_stage_turns` (`stage_id`, `best_turns_used`),
  KEY `idx_user_stage_progress_user_id` (`user_id`),
  CONSTRAINT `fk_user_stage_progress_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Per-player per-stage best clear state used as the source of truth for stage ranking rebuilds.';

CREATE TABLE IF NOT EXISTS `stage_clear_records` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `stage_id` INT NOT NULL,
  `attempt_id` VARCHAR(64) NOT NULL,
  `ruleset_version` INT NOT NULL,
  `turns_used` INT NOT NULL,
  `remaining_basic_cells` INT NOT NULL,
  `total_basic_cells` INT NOT NULL,
  `core_remaining` TINYINT(1) NOT NULL,
  `stars` INT NOT NULL,
  `is_new_best` TINYINT(1) NOT NULL,
  `correlation_id` VARCHAR(36) NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_stage_clear_records_attempt_id` (`attempt_id`),
  KEY `idx_stage_clear_records_user_id` (`user_id`),
  KEY `idx_stage_clear_records_stage_id` (`stage_id`),
  KEY `idx_stage_clear_records_correlation_id` (`correlation_id`),
  CONSTRAINT `fk_stage_clear_records_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Append-only stage clear records for audit and analytics; best state is stored in user_stage_progress.';

CREATE TABLE IF NOT EXISTS `user_ranking_totals` (
  `user_id` BIGINT NOT NULL,
  `total_earned_stars` INT NOT NULL DEFAULT 0,
  `total_stars_achieved_at` DATETIME(6) NULL,
  `max_cleared_stage_id` INT NOT NULL DEFAULT 0,
  `max_stage_achieved_at` DATETIME(6) NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`user_id`),
  KEY `idx_user_ranking_totals_stars` (`total_earned_stars`, `total_stars_achieved_at`),
  KEY `idx_user_ranking_totals_max_stage` (`max_cleared_stage_id`, `max_stage_achieved_at`),
  CONSTRAINT `fk_user_ranking_totals_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Per-player global ranking aggregates rebuilt from user_stage_progress if Redis is lost.';

-- sessions: removed from schema (review before applying):
-- ALTER TABLE `sessions` DROP INDEX `fk_sessions_user_id`;
