-- Generated by db-generator | DB: mysql | 2026-06-09T17:26:28.561Z

ALTER TABLE `players`
  ADD COLUMN `equipped_board_theme_id` INT NOT NULL DEFAULT 1;

-- sessions: removed from schema (review before applying):
-- ALTER TABLE `sessions` DROP INDEX `fk_sessions_user_id`;
