-- Generated by db-generator | DB: mysql | 2026-06-05T07:51:17.095Z

CREATE TABLE IF NOT EXISTS `user_interstitial_state` (
  `user_id` BIGINT NOT NULL,
  `last_shown_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_user_interstitial_state_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tracks last interstitial shown time per player for cooldown enforcement.';

CREATE TABLE IF NOT EXISTS `user_currency` (
  `user_id` BIGINT NOT NULL,
  `soft_amount` BIGINT NOT NULL DEFAULT 0,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_user_currency_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Soft currency balance per player.';

-- sessions: removed from schema (review before applying):
-- ALTER TABLE `sessions` DROP INDEX `fk_sessions_user_id`;
