-- Generated by db-generator | DB: mysql | 2026-06-08T17:00:59.135Z

-- sessions: removed from schema (review before applying):
-- ALTER TABLE `sessions` DROP INDEX `fk_sessions_user_id`;

ALTER TABLE `user_ranking_totals`
  ADD COLUMN `win_streak` INT NOT NULL DEFAULT 0,
  ADD COLUMN `max_win_streak` INT NOT NULL DEFAULT 0;
