-- Generated by db-generator | DB: mysql | 2026-06-04T19:22:35.660Z

CREATE TABLE IF NOT EXISTS `players` (
  `user_id` BIGINT NOT NULL,
  `platform_pid` VARCHAR(24) NOT NULL,
  `display_name` VARCHAR(64) NOT NULL,
  `avatar_id` INT NOT NULL DEFAULT 1,
  `account_created_at` DATETIME(6) NOT NULL,
  `last_login_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `ux_players_platform_pid` (`platform_pid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Game-local player record. platform_pid is the 24-char public cross-reference from platform-auth JWT sub.';

CREATE TABLE IF NOT EXISTS `sessions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `session_id` VARCHAR(24) NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `expires_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_sessions_session_id` (`session_id`),
  CONSTRAINT `fk_sessions_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `event_logs` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `tr_id` INT NOT NULL,
  `correlation_id` VARCHAR(36) NOT NULL,
  `params` JSON NULL,
  `created_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_event_logs_user_id` (`user_id`),
  KEY `idx_event_logs_tr_id` (`tr_id`),
  KEY `idx_event_logs_correlation_id` (`correlation_id`),
  CONSTRAINT `fk_event_logs_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Audit log for all user-modifying API calls.';

CREATE TABLE IF NOT EXISTS `user_stamina_state` (
  `user_id` BIGINT NOT NULL,
  `current_life` INT NOT NULL,
  `last_regen_at` DATETIME(6) NOT NULL,
  `unlimited_until` DATETIME(6) NULL,
  `last_daily_unlimited_claimed_date` DATE NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_user_stamina_state_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Lazy-evaluated life and unlimited stamina state per player.';

CREATE TABLE IF NOT EXISTS `user_reward_claim_state` (
  `user_id` BIGINT NOT NULL,
  `source_id` VARCHAR(64) NOT NULL,
  `period_key` VARCHAR(32) NOT NULL,
  `claim_count` INT NOT NULL DEFAULT 0,
  `last_claimed_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`user_id`, `source_id`, `period_key`),
  KEY `idx_reward_claim_state_user_id` (`user_id`),
  CONSTRAINT `fk_user_reward_claim_state_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Per-player reward source claim state. Event history is stored in event_logs.';

CREATE TABLE IF NOT EXISTS `ad_reward_transactions` (
  `id` VARCHAR(36) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `placement_id` VARCHAR(64) NOT NULL,
  `reward_type` VARCHAR(32) NOT NULL,
  `reward_value` INT NOT NULL,
  `context_type` VARCHAR(32) NULL,
  `context_id` VARCHAR(128) NULL,
  `provider` VARCHAR(32) NOT NULL,
  `provider_tx_id` VARCHAR(128) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `correlation_id` VARCHAR(36) NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `verified_at` DATETIME(6) NULL,
  `granted_at` DATETIME(6) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ad_reward_provider_tx` (`provider`, `provider_tx_id`),
  KEY `idx_ad_reward_user_id` (`user_id`),
  KEY `idx_ad_reward_context` (`context_type`, `context_id`),
  KEY `idx_ad_reward_correlation_id` (`correlation_id`),
  CONSTRAINT `fk_ad_reward_transactions_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Common rewarded-ad transaction table for idempotent verification and grant history.';
