-- Generated by db-generator | DB: mysql | 2026-06-09T17:38:54.204Z

CREATE TABLE IF NOT EXISTS `currency_logs` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `currency_type` VARCHAR(32) NOT NULL,
  `delta` BIGINT NOT NULL,
  `balance_before` BIGINT NOT NULL,
  `balance_after` BIGINT NOT NULL,
  `reason` VARCHAR(256) NOT NULL,
  `correlation_id` VARCHAR(36) NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_currency_logs_user_id` (`user_id`),
  KEY `idx_currency_logs_correlation_id` (`correlation_id`),
  CONSTRAINT `fk_currency_logs_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Append-only audit log for all soft currency mutations. Never UPDATE or DELETE.';

-- sessions: removed from schema (review before applying):
-- ALTER TABLE `sessions` DROP INDEX `fk_sessions_user_id`;
