-- Generated by db-generator | DB: mysql | 2026-06-13T18:51:01.576Z

ALTER TABLE `players`
  ADD COLUMN `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN `conflict_cloud_pid` VARCHAR(24) NULL,
  MODIFY COLUMN `platform_pid` VARCHAR(24) NULL;

-- sessions: removed from schema (review before applying):
-- ALTER TABLE `sessions` DROP INDEX `fk_sessions_user_id`;
