// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/board_theme/board_theme.csv

namespace ProjectFlood.Domain.StaticData;

public class BoardThemeData
{
    public int ThemeId { get; set; }
    public string ResourceName { get; set; } = "";
    public int UnlockCost { get; set; }
    public string UnlockType { get; set; } = "";
    public string DisplayName { get; set; } = "";
}