// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/stage/chapter.csv

namespace ProjectFlood.Domain.StaticData;

public class ChapterData
{
    public int ChapterId { get; set; }
    public int UnlockChapterId { get; set; }
    public int RewardGroupId { get; set; }
}