// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/currency/currency.csv

namespace ProjectFlood.Domain.StaticData;

public class CurrencyData
{
    public int CurrencyId { get; set; }
    public string RewardTypeKey { get; set; } = "";
    public string NameKey { get; set; } = "";
}