// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/item/item.csv
using ProjectFlood.Contracts.GameTypes;

namespace ProjectFlood.Domain.StaticData;

public class ItemData
{
    public int ItemId { get; set; }
    public string NameKey { get; set; } = "";
    public string DescKey { get; set; } = "";
    public ItemUseType UseType { get; set; }
    public ItemEffectType EffectType { get; set; }
    public int EffectValue { get; set; }
}