// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/reward/reward_item.csv

namespace ProjectFlood.Domain.StaticData;

public class RewardItemData
{
    public int RewardGroupId { get; set; }
    public int Version { get; set; }
    public int SortOrder { get; set; }
    public string RewardType { get; set; } = "";
    public int TargetId { get; set; }
    public int Amount { get; set; }
    public int DurationSeconds { get; set; }
    public string StackPolicy { get; set; } = "";
}