// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/stamina/stamina_config.csv

namespace ProjectFlood.Domain.StaticData;

public class StaminaConfigData
{
    public string ConfigId { get; set; } = "";
    public int MaxLife { get; set; }
    public int RegenSeconds { get; set; }
    public int AttemptTimeoutSeconds { get; set; }
    public int MaxRevivePerAttempt { get; set; }
    public int ReviveTurn1 { get; set; }
    public int ReviveTurn2 { get; set; }
    public int ReviveTurn3 { get; set; }
    public int AdLifeRewardAmount { get; set; }
    public string DailyResetTimezone { get; set; } = "";
    public int DailyResetHour { get; set; }
    public string DefaultUnlimitedStackPolicy { get; set; } = "";
}