// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/ad/ad_placement.csv

namespace ProjectLink.Domain.StaticData;

public class AdPlacementData
{
    public string PlacementId { get; set; } = "";
    public int RewardGroupId { get; set; }
    public string ContextType { get; set; } = "";
    public bool IsEnabled { get; set; }
}