// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/common/color_palette.csv

namespace ProjectLink.Domain.StaticData;

public class ColorPaletteData
{
    public byte ColorId { get; set; }
}