// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/reward/reward_source.csv

namespace ProjectLink.Domain.StaticData;

public class RewardSourceData
{
    public string SourceId { get; set; } = "";
    public string SourceType { get; set; } = "";
    public int RewardGroupId { get; set; }
    public int Version { get; set; }
    public string ClaimPolicy { get; set; } = "";
    public int MaxClaims { get; set; }
    public string ResetTimezone { get; set; } = "";
    public int ResetHour { get; set; }
    public string UiSurface { get; set; } = "";
    public bool IsEnabled { get; set; }
}