// AUTO-GENERATED by gen:data — do not edit
#nullable enable
using ProjectFlood.Domain.StaticData;
using ProjectFlood.Generated.Data;

namespace ProjectFlood.Infrastructure.Data;

public partial class StaticDataService
{
    private IReadOnlyDictionary<string, AdPlacementData> _adPlacements = new Dictionary<string, AdPlacementData>();
    private IReadOnlyDictionary<int, AvatarData> _avatars = new Dictionary<int, AvatarData>();
    private IReadOnlyDictionary<int, BoardThemeData> _boardThemes = new Dictionary<int, BoardThemeData>();
    private IReadOnlyDictionary<byte, ColorPaletteData> _colorPalettes = new Dictionary<byte, ColorPaletteData>();
    private IReadOnlyDictionary<string, DynamicResourceData> _dynamicResources = new Dictionary<string, DynamicResourceData>();
    private IReadOnlyDictionary<int, CurrencyData> _currencys = new Dictionary<int, CurrencyData>();
    private IReadOnlyDictionary<int, ItemData> _items = new Dictionary<int, ItemData>();
    private IReadOnlyDictionary<int, RewardGroupData> _rewardGroups = new Dictionary<int, RewardGroupData>();
    private IReadOnlyDictionary<string, RewardSourceData> _rewardSources = new Dictionary<string, RewardSourceData>();
    private IReadOnlyDictionary<int, ChapterData> _chapters = new Dictionary<int, ChapterData>();
    private IReadOnlyDictionary<int, StageData> _stages = new Dictionary<int, StageData>();
    private IReadOnlyDictionary<string, StaminaConfigData> _staminaConfigs = new Dictionary<string, StaminaConfigData>();

    private void InitGeneratedData(string dataRoot)
    {
        var adPath = System.IO.Path.Combine(dataRoot, "ad");
        var avatarPath = System.IO.Path.Combine(dataRoot, "avatar");
        var boardThemePath = System.IO.Path.Combine(dataRoot, "board_theme");
        var commonPath = System.IO.Path.Combine(dataRoot, "common");
        var currencyPath = System.IO.Path.Combine(dataRoot, "currency");
        var itemPath = System.IO.Path.Combine(dataRoot, "item");
        var rewardPath = System.IO.Path.Combine(dataRoot, "reward");
        var stagePath = System.IO.Path.Combine(dataRoot, "stage");
        var staminaPath = System.IO.Path.Combine(dataRoot, "stamina");

        _adPlacements = AdPlacementLoader.LoadAll(System.IO.Path.Combine(adPath, "ad_placement.csv"))
            .ToDictionary(r => r.placement_id, r => new AdPlacementData
            {
                PlacementId = r.placement_id,
                RewardGroupId = r.reward_group_id,
                ContextType = r.context_type,
                IsEnabled = r.is_enabled,
                AdType = r.ad_type,
                CooldownSeconds = r.cooldown_seconds,
                MinStage = r.min_stage,
            });
        _avatars = AvatarLoader.LoadAll(System.IO.Path.Combine(avatarPath, "avatar.csv"))
            .ToDictionary(r => r.avatar_id, r => new AvatarData
            {
                AvatarId = r.avatar_id,
                ResourceName = r.resource_name,
                UnlockCost = r.unlock_cost,
                UnlockType = r.unlock_type,
            });
        _boardThemes = BoardThemeLoader.LoadAll(System.IO.Path.Combine(boardThemePath, "board_theme.csv"))
            .ToDictionary(r => r.theme_id, r => new BoardThemeData
            {
                ThemeId = r.theme_id,
                ResourceName = r.resource_name,
                UnlockCost = r.unlock_cost,
                UnlockType = r.unlock_type,
                DisplayName = r.display_name,
            });
        _colorPalettes = ColorPaletteLoader.LoadAll(System.IO.Path.Combine(commonPath, "color_palette.csv"))
            .ToDictionary(r => r.color_id, r => new ColorPaletteData
            {
                ColorId = r.color_id,
            });
        _dynamicResources = DynamicResourceLoader.LoadAll(System.IO.Path.Combine(commonPath, "dynamic_resource.csv"))
            .ToDictionary(r => r.resource_key, r => new DynamicResourceData
            {
                ResourceKey = r.resource_key,
                SpritePath = r.sprite_path,
                Category = r.category,
                Comment = r.comment,
            });
        _currencys = CurrencyLoader.LoadAll(System.IO.Path.Combine(currencyPath, "currency.csv"))
            .ToDictionary(r => r.currency_id, r => new CurrencyData
            {
                CurrencyId = r.currency_id,
                RewardTypeKey = r.reward_type_key,
                NameKey = r.name_key,
            });
        _items = ItemLoader.LoadAll(System.IO.Path.Combine(itemPath, "item.csv"))
            .ToDictionary(r => r.item_id, r => new ItemData
            {
                ItemId = r.item_id,
                NameKey = r.name_key,
                DescKey = r.desc_key,
                UseType = r.use_type,
                EffectType = r.effect_type,
                EffectValue = r.effect_value,
                Price = r.price,
            });
        _rewardGroups = RewardGroupLoader.LoadAll(System.IO.Path.Combine(rewardPath, "reward_group.csv"))
            .ToDictionary(r => r.reward_group_id, r => new RewardGroupData
            {
                RewardGroupId = r.reward_group_id,
                Version = r.version,
                DisplayKey = r.display_key,
                IsEnabled = r.is_enabled,
            });
        _rewardSources = RewardSourceLoader.LoadAll(System.IO.Path.Combine(rewardPath, "reward_source.csv"))
            .ToDictionary(r => r.source_id, r => new RewardSourceData
            {
                SourceId = r.source_id,
                SourceType = r.source_type,
                RewardGroupId = r.reward_group_id,
                Version = r.version,
                ClaimPolicy = r.claim_policy,
                MaxClaims = r.max_claims,
                ResetTimezone = r.reset_timezone,
                ResetHour = r.reset_hour,
                UiSurface = r.ui_surface,
                IsEnabled = r.is_enabled,
            });
        _chapters = ChapterLoader.LoadAll(System.IO.Path.Combine(stagePath, "chapter.csv"))
            .ToDictionary(r => r.chapter_id, r => new ChapterData
            {
                ChapterId = r.chapter_id,
                UnlockChapterId = r.unlock_chapter_id,
                RewardGroupId = r.reward_group_id,
            });
        _stages = StageLoader.LoadAll(System.IO.Path.Combine(stagePath, "stage.csv"))
            .ToDictionary(r => r.stage_id, r => new StageData
            {
                StageId = r.stage_id,
                ChapterId = r.chapter_id,
                BoardWidth = r.board_width,
                BoardHeight = r.board_height,
                TurnLimit = r.turn_limit,
                Star1Ratio = r.star1_ratio,
                Star2Ratio = r.star2_ratio,
                Cells = r.cells,
                VerifiedSolution = r.verified_solution,
                RulesetVersion = r.ruleset_version,
                RewardGroupId = r.reward_group_id,
                RotationInterval = r.rotation_interval,
                PortalData = r.portal_data,
                ConveyorData = r.conveyor_data,
            });
        _staminaConfigs = StaminaConfigLoader.LoadAll(System.IO.Path.Combine(staminaPath, "stamina_config.csv"))
            .ToDictionary(r => r.config_id, r => new StaminaConfigData
            {
                ConfigId = r.config_id,
                MaxLife = r.max_life,
                RegenSeconds = r.regen_seconds,
                AttemptTimeoutSeconds = r.attempt_timeout_seconds,
                MaxRevivePerAttempt = r.max_revive_per_attempt,
                ReviveTurn1 = r.revive_turn_1,
                ReviveTurn2 = r.revive_turn_2,
                ReviveTurn3 = r.revive_turn_3,
                AdLifeRewardAmount = r.ad_life_reward_amount,
                DailyResetTimezone = r.daily_reset_timezone,
                DailyResetHour = r.daily_reset_hour,
                DefaultUnlimitedStackPolicy = r.default_unlimited_stack_policy,
            });
    }

    public AdPlacementData? GetAdPlacement(string placement_id) => _adPlacements.GetValueOrDefault(placement_id);
    public IReadOnlyList<AdPlacementData> GetAllAdPlacements() => _adPlacements.Values.ToList();
    public AvatarData? GetAvatar(int avatar_id) => _avatars.GetValueOrDefault(avatar_id);
    public IReadOnlyList<AvatarData> GetAllAvatars() => _avatars.Values.ToList();
    public BoardThemeData? GetBoardTheme(int theme_id) => _boardThemes.GetValueOrDefault(theme_id);
    public IReadOnlyList<BoardThemeData> GetAllBoardThemes() => _boardThemes.Values.ToList();
    public ColorPaletteData? GetColorPalette(byte color_id) => _colorPalettes.GetValueOrDefault(color_id);
    public IReadOnlyList<ColorPaletteData> GetAllColorPalettes() => _colorPalettes.Values.ToList();
    public DynamicResourceData? GetDynamicResource(string resource_key) => _dynamicResources.GetValueOrDefault(resource_key);
    public IReadOnlyList<DynamicResourceData> GetAllDynamicResources() => _dynamicResources.Values.ToList();
    public CurrencyData? GetCurrency(int currency_id) => _currencys.GetValueOrDefault(currency_id);
    public IReadOnlyList<CurrencyData> GetAllCurrencys() => _currencys.Values.ToList();
    public ItemData? GetItem(int item_id) => _items.GetValueOrDefault(item_id);
    public IReadOnlyList<ItemData> GetAllItems() => _items.Values.ToList();
    public RewardGroupData? GetRewardGroup(int reward_group_id) => _rewardGroups.GetValueOrDefault(reward_group_id);
    public IReadOnlyList<RewardGroupData> GetAllRewardGroups() => _rewardGroups.Values.ToList();
    public RewardSourceData? GetRewardSource(string source_id) => _rewardSources.GetValueOrDefault(source_id);
    public IReadOnlyList<RewardSourceData> GetAllRewardSources() => _rewardSources.Values.ToList();
    public ChapterData? GetChapter(int chapter_id) => _chapters.GetValueOrDefault(chapter_id);
    public IReadOnlyList<ChapterData> GetAllChapters() => _chapters.Values.ToList();
    public StageData? GetStage(int stage_id) => _stages.GetValueOrDefault(stage_id);
    public IReadOnlyList<StageData> GetAllStages() => _stages.Values.ToList();
    public StaminaConfigData? GetStaminaConfig(string config_id) => _staminaConfigs.GetValueOrDefault(config_id);
    public IReadOnlyList<StaminaConfigData> GetAllStaminaConfigs() => _staminaConfigs.Values.ToList();
}