// AUTO-GENERATED by gen:data — do not edit
#nullable enable
using ProjectFlood.Domain.StaticData;

namespace ProjectFlood.Domain.Interfaces;

public partial interface IStaticDataService
{
    AdPlacementData? GetAdPlacement(string placement_id);
    IReadOnlyList<AdPlacementData> GetAllAdPlacements();
    AvatarData? GetAvatar(int avatar_id);
    IReadOnlyList<AvatarData> GetAllAvatars();
    ColorPaletteData? GetColorPalette(byte color_id);
    IReadOnlyList<ColorPaletteData> GetAllColorPalettes();
    ItemData? GetItem(int item_id);
    IReadOnlyList<ItemData> GetAllItems();
    RewardGroupData? GetRewardGroup(int reward_group_id);
    IReadOnlyList<RewardGroupData> GetAllRewardGroups();
    RewardSourceData? GetRewardSource(string source_id);
    IReadOnlyList<RewardSourceData> GetAllRewardSources();
    ChapterData? GetChapter(int chapter_id);
    IReadOnlyList<ChapterData> GetAllChapters();
    StageData? GetStage(int stage_id);
    IReadOnlyList<StageData> GetAllStages();
    StaminaConfigData? GetStaminaConfig(string config_id);
    IReadOnlyList<StaminaConfigData> GetAllStaminaConfigs();
}