// AUTO-GENERATED by gen:data — do not edit
#nullable enable
using ProjectLink.Domain.StaticData;

namespace ProjectLink.Domain.Interfaces;

public partial interface IStaticDataService
{
    ColorPaletteData? GetColorPalette(byte color_id);
    IReadOnlyList<ColorPaletteData> GetAllColorPalettes();
    StageData? GetStage(int stage_id);
    IReadOnlyList<StageData> GetAllStages();
}